// data/members.ts

export interface Menu {
  id: number;
  name: string;
  price: number;
  category: string;
}

export const menu: Menu[] = [
  { id: 1, name: 'Grilled Chicken Wrap', price: 140, category: 'Non-Veg Wrap' },
  { id: 2, name: 'Roasted Chicken Breast Wrap', price: 140, category: 'Non-Veg Wrap' },
  { id: 3, name: 'Chicken Tikka Wrap', price: 150, category: 'Non-Veg Wrap' },
  { id: 4, name: 'Chicken Kabab Wrap', price: 150, category: 'Non-Veg Wrap' },
  { id: 5, name: 'Chicken Makhani Wrap', price: 150, category: 'Non-Veg Wrap' },
  { id: 6, name: 'Chicken Cheese Wrap', price: 160, category: 'Non-Veg Wrap' },
  { id: 7, name: 'Chicken Shawarma Wrap', price: 180, category: 'Non-Veg Wrap' },
  { id: 8, name: 'Potato Herbs Wrap', price: 100, category: 'Veg Wrap' },
  { id: 9, name: 'Grilled Tofu Wrap', price: 110, category: 'Veg Wrap' },
  { id: 10, name: 'Grilled Paneer Wrap', price: 120, category: 'Veg Wrap' },
  { id: 11, name: 'Paneer Tikka Wrap', price: 140, category: 'Veg Wrap' },
  { id: 12, name: 'Paneer Makhani Wrap', price: 150, category: 'Veg Wrap' },
  { id: 13, name: 'Soya Chikki Wrap', price: 140, category: 'Veg Wrap' },
  { id: 14, name: 'Veg Shami Kabab Wrap', price: 140, category: 'Veg Wrap' },
  { id: 15, name: 'Onion Tomato Poha', price: 80, category: 'Poha' },
  { id: 16, name: 'English Veggie Poha', price: 100, category: 'Poha' },
  { id: 17, name: 'Tofu Poha', price: 110, category: 'Poha' },
  { id: 18, name: 'Paneer Poha', price: 120, category: 'Poha' },
  { id: 19, name: 'Paneer Bhurji Poha', price: 120, category: 'Poha' },
  { id: 20, name: 'Egg Bhurji Poha', price: 130, category: 'Poha' },
  { id: 21, name: 'Grill Chicken Poha', price: 130, category: 'Poha' },
  { id: 22, name: 'Chicken Keema Poha', price: 130, category: 'Poha' },
  { id: 23, name: 'Boiled Eggs (5 pcs)', price: 60, category: 'Egg Dish' },
  { id: 24, name: 'Masala Omelette', price: 80, category: 'Egg Dish' },
  { id: 25, name: 'Half-fry Omelette', price: 100, category: 'Egg Dish' },
  { id: 26, name: 'English Veggies Omelette', price: 110, category: 'Egg Dish' },
  { id: 27, name: 'Cheese Omelette', price: 120, category: 'Egg Dish' },
  { id: 28, name: 'English Veggies Cheese Omelette', price: 150, category: 'Egg Dish' },
  { id: 29, name: 'Chicken Omelette', price: 130, category: 'Egg Dish' },
  { id: 30, name: 'Chicken Cheese Omelette', price: 180, category: 'Egg Dish' },
  { id: 31, name: 'Chicken Keema Omelette', price: 180, category: 'Egg Dish' },
  { id: 32, name: 'White Sauce Pasta', price: 150, category: 'Pasta' },
  { id: 33, name: 'Red Sauce Pasta', price: 150, category: 'Pasta' },
  { id: 34, name: 'Mix Sauce Pasta', price: 150, category: 'Pasta' },
  { id: 35, name: 'Pesto Pasta', price: 150, category: 'Pasta' },
  { id: 36, name: 'Steam Egg White Salad', price: 150, category: 'Non-Veg Salad' },
  { id: 37, name: 'Steam Chicken Salad', price: 170, category: 'Non-Veg Salad' },
  { id: 38, name: 'Grill Chicken Salad', price: 180, category: 'Non-Veg Salad' },
  { id: 39, name: 'Chicken Kabab Salad', price: 190, category: 'Non-Veg Salad' },
  { id: 40, name: 'Chicken Tikka Salad', price: 190, category: 'Non-Veg Salad' },
  { id: 41, name: 'High Protein Non-Veg Salad', price: 220, category: 'Non-Veg Salad' },
  { id: 42, name: 'Chicken Shawarma Salad', price: 190, category: 'Non-Veg Salad' },
  { id: 43, name: 'Roasted Chicken Breast Salad', price: 190, category: 'Non-Veg Salad' },
  { id: 44, name: 'Mix Sprout Salad', price: 130, category: 'Veg Salad' },
  { id: 45, name: 'Green Garden Salad', price: 150, category: 'Veg Salad' },
  { id: 46, name: 'Grill Tofu Salad', price: 150, category: 'Veg Salad' },
  { id: 47, name: 'Roasted Tofu Salad', price: 170, category: 'Veg Salad' },
  { id: 48, name: 'Grill Paneer Salad', price: 170, category: 'Veg Salad' },
  { id: 49, name: 'Beans Salad', price: 180, category: 'Veg Salad' },
  { id: 50, name: 'Paneer Tikka Salad', price: 180, category: 'Veg Salad' },
  { id: 51, name: 'Soya Chikki Salad', price: 190, category: 'Veg Salad' },

  { id: 52, name: 'Steam Egg White Sub', price: 140, category: 'Non-Veg Sub' },
  { id: 53, name: 'Grilled Chicken Sub', price: 150, category: 'Non-Veg Sub' },
  { id: 54, name: 'Chicken Kabab Sub', price: 170, category: 'Non-Veg Sub' },
  { id: 55, name: 'Chicken Tikka Sub', price: 170, category: 'Non-Veg Sub' },
  { id: 56, name: 'Grilled Chicken Cheese Sub', price: 180, category: 'Non-Veg Sub' },
  { id: 57, name: 'Egg Chicken Sub', price: 180, category: 'Non-Veg Sub' },
  { id: 58, name: 'Chicken Makhani Sub', price: 180, category: 'Non-Veg Sub' },
  { id: 59, name: 'Chicken Shawarma Sub', price: 180, category: 'Non-Veg Sub' },
  { id: 60, name: 'English Veggie Sub', price: 130, category: 'Veg Sub' },
  { id: 61, name: 'Grill Tofu Sub', price: 140, category: 'Veg Sub' },
  { id: 62, name: 'Grill Paneer Sub', price: 150, category: 'Veg Sub' },
  { id: 63, name: 'Roasted Tofu Sub', price: 160, category: 'Veg Sub' },
  { id: 64, name: 'Paneer Tikka Sub', price: 170, category: 'Veg Sub' },
  { id: 65, name: 'Paneer Makhani Sub', price: 170, category: 'Veg Sub' },
  { id: 66, name: 'Pesto Paneer Sub', price: 170, category: 'Veg Sub' },
  { id: 67, name: 'Cheese Potato Herbs Sub', price: 170, category: 'Veg Sub' },
  { id: 68, name: 'Veg Shami Kabab Sub', price: 170, category: 'Veg Sub' },
  { id: 69, name: 'Soya Chikki Sub', price: 170, category: 'Veg Sub' },
  { id: 70, name: 'Steam Egg White Rice Bowl', price: 150, category: 'Non-Veg Rice Bowl' },
  { id: 71, name: 'Egg Bhurji Rice Bowl', price: 150, category: 'Non-Veg Rice Bowl' },
  { id: 72, name: 'Steam Chicken Rice Bowl', price: 170, category: 'Non-Veg Rice Bowl' },
  { id: 73, name: 'Grilled Chicken Rice Bowl', price: 180, category: 'Non-Veg Rice Bowl' },
  { id: 74, name: 'Chicken Kabab Rice Bowl', price: 190, category: 'Non-Veg Rice Bowl' },
  { id: 75, name: 'Roasted Chicken Breast Rice Bowl', price: 180, category: 'Non-Veg Rice Bowl' },
  { id: 76, name: 'Chicken Tikka Rice Bowl', price: 190, category: 'Non-Veg Rice Bowl' },
  { id: 77, name: 'Egg Chicken Rice Bowl', price: 190, category: 'Non-Veg Rice Bowl' },
  { id: 78, name: 'Chicken Shawarma Rice Bowl', price: 190, category: 'Non-Veg Rice Bowl' },
  { id: 79, name: 'English Veggies Rice Bowl', price: 130, category: 'Veg Rice Bowl' },
  { id: 80, name: 'Grilled Tofu Rice Bowl', price: 140, category: 'Veg Rice Bowl' },
  { id: 81, name: 'Roasted Tofu Rice Bowl', price: 150, category: 'Veg Rice Bowl' },
  { id: 82, name: 'Grilled Paneer Rice Bowl', price: 160, category: 'Veg Rice Bowl' },
  { id: 83, name: 'Paneer Tikka Rice Bowl', price: 170, category: 'Veg Rice Bowl' },
  { id: 84, name: 'Paneer Bhurji Rice Bowl', price: 160, category: 'Veg Rice Bowl' },
  { id: 85, name: 'Beans Rice Bowl', price: 160, category: 'Veg Rice Bowl' },
  { id: 86, name: 'Soya Chikki Rice Bowl', price: 190, category: 'Veg Rice Bowl' },
  { id: 87, name: 'Soya Kabab Rice Bowl', price: 190, category: 'Veg Rice Bowl' },
];

